service: notes-api

# Create an optimized package for our functions
# By default Serverless Framework creates a single package for all your Lambda functions.
# This means that when a Lambda function is invoked, it’ll load all the code in your app.
# Including all the other Lambda functions. This negatively affects performance as your app grows in size.
# The larger your Lambda function packages, the longer the cold starts.
package:
  individually: true # Serverless Framework is packaging our functions individually, add the following to your

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
